{
 "title": "All server telegraf",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Container",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Stopped Container",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_stopped" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Running containers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_running" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total images",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_images" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory  Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory  Utilization",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 10, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "table",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "limit": "1",
       "measurement": "docker_container_status",
       "select": [
        [
         { "params": [ "uptime_ns" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Website Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Result code",
     "type": "stat",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "http_response_code" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "response_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Multiple server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads (All-server)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "total_threads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Uptime (All- server)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Logged in User( All -server)",
     "type": "stat",
     "description": "number of user logged in ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "n_users" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total processes (All -server)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk utilization (All- server)",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 7, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory Utilization(All-server)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory Utilization(All-server)",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 3, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Utilization(All-server)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Utilization(All-server)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}