{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time()-node_boot_time_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk utilization (All- server)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) - (node_filesystem_free_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU utilization(All-server)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_cpu_seconds:percentage",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory status",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "total:{{instance}}" },
    { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "free:{{instance}}" },
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{}",
     "legendFormat": "used:{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization(irate1m)(All-server)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:node_cpu_seconds:irate1m"
    }
   ]
  },
  {
   "title": "Disk utilization (All- server)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(100 * ((node_filesystem_free_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} )  / (node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) ))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "free disk space ",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (mountpoint,instance) (node_filesystem_avail_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}